### ISSUE TITLE
rotateTicks rotates ticks and labels

### ISSUE THREAD

**Issue by dpedowitz** [jiahuang/d3-timeline#22]
adding rotateTicks when you have times with labels rotates the ticks and the labels.

here's a patch to just rotate ticks:

      if (rotateTicks) {
        g.selectAll(".tick text")
          .attr("transform", function(d) {
            return "rotate(" + rotateTicks + ")translate("
              + (this.getBBox().width / 2 + 10) + "," // TODO: change this 10
              + this.getBBox().height / 2 + ")";
          });
      }

**Comment by TJMcDonald** [comment]
I had to change g.selectAll(".tick text") to g.selectAll(".tick + text") to get it to work. I noticed that the text element follows the line element for the tick mark.

**Comment by jiahuang** [comment]
Thanks @dpedowitz. I've merged the fix.
