### ISSUE TITLE
does it work for dates (not times)?

### ISSUE THREAD

**Issue by dpdonohue** [jiahuang/d3-timeline#45]
All your examples seem to show just time of a day.
Can your timeline represent multiple years?

**Comment by Jonwheeler** [comment]
Yes, you should be able to. I've been using this with dates that span multiple years. You pass the chart unix timestamps in milliseconds. You can then pass options to `tickFormat()`

e.g.

```javascript
{
  format: d3.time.format("%I %p"),
  tickTime: d3.time.hours,
  tickInterval: 1,
  tickSize: 6
}
```

**Comment by dpdonohue** [comment]
Hey thanks Jon that is helpful.  This is a great tool
