### ISSUE TITLE
No labels on gant chart 

### ISSUE THREAD

**Issue by SteveStrong** [jiahuang/d3-timeline#61]
Looks like the gant chart examples do not show labels on the left.  This is shown in the PNG's but none of these examples show code that will product the picture

               var labelTestData = [ 
                 {label: "person a", times: [{"starting_time": 1355752800000, "ending_time": 1355759900000}, {"starting_time": 1355767900000, "ending_time": 1355774400000}]}, 
                 {label: "person b", times: [{"starting_time": 1355759910000, "ending_time": 1355761900000}, ]}, 
                 {label: "person c", times: [{"starting_time": 1355761910000, "ending_time": 1355763910000}]}, 
                ];

**Comment by patte** [comment]
+1

**Comment by awsp** [comment]
Got the same problem. 

Not sure if it is intended or a bug, to correctly display text value, you will need to provide a format function for label. 

For example, 
```js
d3.timeline().stack().labelFormat(function(label){
  return label;
})
```

**Comment by jiahuang** [comment]
Sorry for the wait, been out of the country. I've merged that PR.
