### ISSUE TITLE
Text alignment

### ISSUE THREAD

**Issue by marcbowes** [jiahuang/d3-timeline#69]
In the readme: https://github.com/jiahuang/d3-timeline/blob/master/examples/timeline4.png

"person" is vertically aligned with the bar. This is pleasing! :+1: 

However, when I look at the example (https://github.com/jiahuang/d3-timeline/blob/master/examples/example.html) it is not well aligned at all. "person" is shifted down several pixels. (See screenshot.)

I literally downloaded the example, so I'm not sure what I could have done wrong:

* clone the repro to `/tmp`
* Open file:///tmp/d3-timeline/examples/example.html in Firefox on OSX

<img width="514" alt="mozilla_firefox" src="https://cloud.githubusercontent.com/assets/15209/8600960/3c7847ce-2669-11e5-8c5a-e17edddd6843.png">

**Comment by inodb** [comment]
Things seem to be alright in this commit:

http://rawgit.com/jiahuang/d3-timeline/081e83b4926708b9e1822aa3d3e5e5541a5abc84/examples/example.html

Looks like the latest released version also has an issue where the labels disappear:

http://rawgit.com/jiahuang/d3-timeline/1b21c455faee5cf9f786956eefbf09530c63be1d/examples/example.html

**Comment by inodb** [comment]
This looks like a duplicate of #68 btw

**Comment by marcbowes** [comment]
Oops, thanks.
