### ISSUE TITLE
spelling of .rowSeperators(color)

### ISSUE THREAD

**Issue by ryanfox** [jiahuang/d3-timeline#77]
The word "sepArators" is spelled with an a, not an e as in "sepErators".  If changing the name of the function isn't desirable due to breaking backwards compatibility, perhaps adding a wrapper function with the correct spelling could be useful?

**Comment by dperciva** [comment]
There's an outstanding pull request [#75](https://github.com/jiahuang/d3-timeline/pull/75) from @danhunsaker that corrects this spelling, though it doesn't include the wrapper for compatibility that you suggested.

**Comment by danhunsaker** [comment]
Said wrapper would probably be a good idea...

**Comment by inodb** [comment]
Thanks for your suggestions. Added @danhunsaker's changes now w/o wrapper. I think it's fine to break compatibility at this stage of development.
